version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      - "4318:4318"

  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    command: --config.file=/etc/prometheus/prometheus.yml --no-scrape.adjust-timestamps
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.0.1
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
  zk1:
    restart: always
    image: zookeeper:3.9.0
    container_name: zk1
    ports:
      - "2181:2181" # Zookeeper Client
      #- "2888:2888" # Zookeeper Follower
      #- "3888:3888" # Zookeeper Election
      #- "8080:8080" # AdminServer
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    restart: always
    image: zookeeper:3.9.0
    container_name: zk2
    ports:
      - "2182:2181" # Zookeeper Client
      #- "2888:2888" # Zookeeper Follower
      #- "3888:3888" # Zookeeper Election
      #- "8080:8080" # AdminServer
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    restart: always
    image: zookeeper:3.9.0
    container_name: zk3
    ports:
      - "2183:2181" # Zookeeper Client
      #- "2888:2888" # Zookeeper Follower
      #- "3888:3888" # Zookeeper Election
      #- "8080:8080" # AdminServer
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
